"""commit

Revision ID: 8e210c05273f
Revises: b8e0ac3699a3
Create Date: 2022-08-23 16:35:18.296566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e210c05273f'
down_revision = 'b8e0ac3699a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
